site_name: Árvores
theme:
  name: material
  language: pt
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tabs

nav:
  - Página Inicial: index.md
  - Apresentação: apresentacao.md
  - Introdução: introducao.md
  - Tarefa: tarefa.md
  - Processo: processo.md
  - Fontes de Informação: fontes_de_informacao.md
  - Avaliação: avaliacao.md
  - Conclusão: conclusao.md
  - Créditos: creditos.md

extra_css:
  - css/extra.css

extra:
  generator: false
